// ignore_for_file: constant_identifier_names

part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const MY_RIDES_REQUEST = _Paths.MY_RIDES_REQUEST;
  static const MESSAGES = _Paths.MESSAGES;
  static const PROFILE = _Paths.PROFILE;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const ORIGIN = _Paths.ORIGIN;
  static const DESTINATION = _Paths.DESTINATION;
  static const ADD_STOPS = _Paths.ADD_STOPS;
  static const CHAT_PAGE = _Paths.CHAT_PAGE;
  static const CREATE_ACCOUNT = _Paths.CREATE_ACCOUNT;
  static const VERIFY = _Paths.VERIFY;
  static const TERMS_CONDITIONS = _Paths.TERMS_CONDITIONS;
  static const LOGIN = _Paths.LOGIN;
  static const ABOUT = _Paths.ABOUT;
  static const PROFILE_SETUP = _Paths.PROFILE_SETUP;
  static const PROFILE_SETTINGS = _Paths.PROFILE_SETTINGS;
  static const USER_DETAILS = _Paths.USER_DETAILS;
  static const VEHICLE_DETAILS = _Paths.VEHICLE_DETAILS;
  static const EMERGENCY_CONTACTS = _Paths.EMERGENCY_CONTACTS;
  static const PUSH_NOTIFICATIONS = _Paths.PUSH_NOTIFICATIONS;
  static const STUDENT_DISCOUNTS = _Paths.STUDENT_DISCOUNTS;
  static const REFER_FRIENDS = _Paths.REFER_FRIENDS;
  static const REPORT_BLOCK = _Paths.REPORT_BLOCK;
  static const REFER_FRIENDS_ADD_CONTACT = _Paths.REFER_FRIENDS_ADD_CONTACT;
  static const FILE_DISPUTE = _Paths.FILE_DISPUTE;
  static const RIDE_HISTORY = _Paths.RIDE_HISTORY;
  static const RIDE_DETAILS = _Paths.RIDE_DETAILS;
  static const REPORT = _Paths.REPORT;
  static const HELP_SUPPORT = _Paths.HELP_SUPPORT;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const CARPOOL_SCHEDULE = _Paths.CARPOOL_SCHEDULE;
  static const GUIDELINES_VIEW = _Paths.GUIDELINES_VIEW;
  static const PRICING_VIEW = _Paths.PRICING_VIEW;
  static const BOTTOM_NAVIGATION = _Paths.BOTTOM_NAVIGATION;
  static const FIND_RIDE = _Paths.FIND_RIDE;

  static const CREATE_NEW_EVENT = _Paths.CREATE_NEW_EVENT;
  static const EVENT_DETAILS = _Paths.EVENT_DETAILS;
  static const ORGANIZE_CARPOOL = _Paths.ORGANIZE_CARPOOL;
  static const GROUP_CHAT = _Paths.GROUP_CHAT;
  static const GROUP_DESTINATION = _Paths.GROUP_DESTINATION;


  static const MATCHING_RIDES = _Paths.MATCHING_RIDES;
  static const DRIVER_DETAILS = _Paths.DRIVER_DETAILS;
  static const RIDER_PROFILE_SETUP = _Paths.RIDER_PROFILE_SETUP;
  static const RIDER_POST_RIDE = _Paths.RIDER_POST_RIDE;
  static const RIDER_MY_RIDE_REQUEST = _Paths.RIDER_MY_RIDE_REQUEST;
  static const RIDER_FILTER = _Paths.RIDER_FILTER;
  static const RIDER_MY_RIDES = _Paths.RIDER_MY_RIDES;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const MY_RIDES_ONE_TIME = _Paths.MY_RIDES_ONE_TIME;
  static const MY_RIDES_RECURRING = _Paths.MY_RIDES_RECURRING;
  static const FORGOT_PASSWORD_OTP = _Paths.FORGOT_PASSWORD_OTP;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const PASSWORD_CHANGED = _Paths.PASSWORD_CHANGED;
  static const MY_RIDES_DETAILS = _Paths.MY_RIDES_DETAILS;
  static const MY_RIDES_PAGE = _Paths.MY_RIDES_PAGE;
  static const RIDER_MY_RIDES_DETAILS = _Paths.RIDER_MY_RIDES_DETAILS;
  static const RIDER_MY_RIDES_SEND_DETAILS = _Paths.RIDER_MY_RIDES_SEND_DETAILS;
  static const RIDER_MY_RIDES_CONFIRM_DETAILS =
      _Paths.RIDER_MY_RIDES_CONFIRM_DETAILS;
  static const RIDER_CONFIRMED_RIDE_DETAILS =
      _Paths.RIDER_CONFIRMED_RIDE_DETAILS;
  static const START_RIDE = _Paths.START_RIDE;
  static const POST_RIDE_STEP_ONE = _Paths.POST_RIDE_STEP_ONE;
  static const MY_RIDES_RECURRING_DETAILS = _Paths.MY_RIDES_RECURRING_DETAILS;
  static const RATING_DRIVER_SIDE = _Paths.RATING_DRIVER_SIDE;
  static const RATING_RIDER_SIDE = _Paths.RATING_RIDER_SIDE;
  static const RIDER_START_RIDE_MAP = _Paths.RIDER_START_RIDE_MAP;
  static const SUBMIT_DISPUTE = _Paths.SUBMIT_DISPUTE;
  static const POST_RIDE_STEP_TWO = _Paths.POST_RIDE_STEP_TWO;
  static const POST_RIDE_STEP_THREE = _Paths.POST_RIDE_STEP_THREE;
  static const MAP_DRIVER_CONFIRM_REQUEST = _Paths.MAP_DRIVER_CONFIRM_REQUEST;
  static const MAP_DRIVER_SEND_REQUEST = _Paths.MAP_DRIVER_SEND_REQUEST;
  static const VERIFICATION_DONE = _Paths.VERIFICATION_DONE;
  static const POLICY_CANCELLATION = _Paths.POLICY_CANCELLATION;
  static const POLICY_PRIVACY = _Paths.POLICY_PRIVACY;
  static const WALLET = _Paths.WALLET;
  static const WALLET_ADD_MONEY = _Paths.WALLET_ADD_MONEY;
  static const WALLET_TO_BANK_ACC = _Paths.WALLET_TO_BANK_ACC;
  static const TRANSACTION_HISTORY = _Paths.TRANSACTION_HISTORY;
  static const PAYMENT_METHOD = _Paths.PAYMENT_METHOD;
  static const PAYMENT = _Paths.PAYMENT;
  static const PAYNOW = _Paths.PAYNOW;
  static const ADD_CARD = _Paths.ADD_CARD;
  static const ADD_BANK_DETAILS = _Paths.ADD_BANK_DETAILS;
  static const SEARCH_ADDRESS = _Paths.SEARCH_ADDRESS;
  static const POST_RIDE_STEP_FOUR = _Paths.POST_RIDE_STEP_FOUR;
  static const MAP_RIDER_CONFIRM_REQUEST = _Paths.MAP_RIDER_CONFIRM_REQUEST;
  static const MAP_RIDER_SEND_REQUEST = _Paths.MAP_RIDER_SEND_REQUEST;
  static const VEHICLE_SETUP = _Paths.VEHICLE_SETUP;
  static const WEB_ADD_PAY = _Paths.WEB_ADD_PAY;
  static const ADD_GIFT = _Paths.ADD_GIFT;
  static const CHAT_WITH_EXPERTS = _Paths.CHAT_WITH_EXPERTS;
  static const WEB_ADD_TO_BANK = _Paths.WEB_ADD_TO_BANK;
  static const MY_RIDES_CONFIRM_DETAILS = _Paths.MY_RIDES_CONFIRM_DETAILS;
  static const ARCHIVED = _Paths.ARCHIVED;
  static const LANGUAGE = _Paths.LANGUAGE;
  static const MY_RIDES_EDIT = _Paths.MY_RIDES_EDIT;
  static const PREVIOUS_RIDES = _Paths.PREVIOUS_RIDES;
  static const PREV_POSTED = _Paths.PREV_POSTED;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const BOTTOM_NAVIGATION = '/bottom_navigation_view';
  static const SPLASH = '/splash';
  static const ONBOARDING = '/onboarding';
  static const MESSAGES = '/messages';
  static const PROFILE = '/profile';
  static const NOTIFICATIONS = '/notifications';
  static const ORIGIN = '/origin';
  static const DESTINATION = '/destination';
  static const ADD_STOPS = '/add-stops';
  static const CHAT_PAGE = '/chat-page';
  static const CREATE_ACCOUNT = '/create-account';
  static const VERIFY = '/verify';
  static const TERMS_CONDITIONS = '/terms-conditions';
  static const MY_RIDES_REQUEST = '/my_rides_request';
  static const LOGIN = '/login';
  static const ABOUT = '/about';
  static const PROFILE_SETUP = '/profile-setup';
  static const PROFILE_SETTINGS = '/profile-settings';
  static const CARPOOL_SCHEDULE = '/carpool_schedule_view.dart';
  static const GUIDELINES_VIEW = '/guidelines_view.dart';
  static const PRICING_VIEW = '/pricing_view.dart';
  static const USER_DETAILS = '/user-details';
  static const VEHICLE_DETAILS = '/vehicle-details';
  static const EMERGENCY_CONTACTS = '/emergency-contacts';
  static const PUSH_NOTIFICATIONS = '/push-notifications';
  static const STUDENT_DISCOUNTS = '/student-discounts';
  static const REFER_FRIENDS = '/refer-frinds';
  static const REPORT_BLOCK = '/report-block';
  static const REFER_FRIENDS_ADD_CONTACT = '/refer-frinds-add-contact';
  static const FILE_DISPUTE = '/file-dispute';
  static const RIDE_HISTORY = '/ride-history';
  static const RIDE_DETAILS = '/ride-details';
  static const REPORT = '/report';
  static const HELP_SUPPORT = '/help-support';
  static const CHANGE_PASSWORD = '/change-password';
  static const FIND_RIDE = '/find-ride';

  static const CREATE_NEW_EVENT = '/create-new-event';
  static const EVENT_DETAILS = '/event-details';
  static const ORGANIZE_CARPOOL = '/organize-carpool';
  static const GROUP_CHAT = '/group-chat';
  static const GROUP_DESTINATION = '/group-destination';



  static const MATCHING_RIDES = '/matching-rides';
  static const DRIVER_DETAILS = '/driver-details';
  static const RIDER_PROFILE_SETUP = '/rider-profile-setup';
  static const RIDER_POST_RIDE = '/rider-post-ride';
  static const RIDER_MY_RIDE_REQUEST = '/rider-ride-request';
  static const RIDER_FILTER = '/rider-filter';
  static const RIDER_MY_RIDES = '/rider-my-rides';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const MY_RIDES_ONE_TIME = '/my-rides-one-time';
  static const MY_RIDES_RECURRING = '/my-rides-recurring';
  static const FORGOT_PASSWORD_OTP = '/forgot-password-otp';
  static const RESET_PASSWORD = '/reset-password';
  static const PASSWORD_CHANGED = '/password-changed';
  static const MY_RIDES_DETAILS = '/my-rides-details';
  static const MY_RIDES_PAGE = '/my-rides-page';
  static const RIDER_MY_RIDES_DETAILS = '/rider-my-rides-details';
  static const RIDER_MY_RIDES_SEND_DETAILS = '/rider-my-rides-send-details';
  static const RIDER_MY_RIDES_CONFIRM_DETAILS =
      '/rider-my-rides-confirm-details';
  static const RIDER_CONFIRMED_RIDE_DETAILS = '/rider-confirmed-ride-details';
  static const START_RIDE = '/start-ride';
  static const POST_RIDE_STEP_ONE = '/post-ride-step-one';
  static const MY_RIDES_RECURRING_DETAILS = '/my-rides-recurring-details';
  static const RATING_DRIVER_SIDE = '/rating-driver-side';
  static const RATING_RIDER_SIDE = '/rating-rider-side';
  static const RIDER_START_RIDE_MAP = '/rider-start-ride-map';
  static const SUBMIT_DISPUTE = '/submit-dispute';
  static const POST_RIDE_STEP_TWO = '/post-ride-step-two';
  static const POST_RIDE_STEP_THREE = '/post-ride-step-three';
  static const MAP_DRIVER_CONFIRM_REQUEST = '/map-driver-confirm-request';
  static const MAP_DRIVER_SEND_REQUEST = '/map-driver-send-request';
  static const VERIFICATION_DONE = '/verification-done';
  static const POLICY_CANCELLATION = '/policy-cancellation';
  static const POLICY_PRIVACY = '/policy-privacy';
  static const WALLET = '/wallet';
  static const WALLET_ADD_MONEY = '/wallet-add-money';
  static const WALLET_TO_BANK_ACC = '/wallet-to-bank-acc';
  static const TRANSACTION_HISTORY = '/transaction-history';
  static const PAYMENT_METHOD = '/payment-method';
  static const PAYMENT = '/payment';
  static const PAYNOW = '/pay-now';
  static const ADD_CARD = '/add-card';
  static const ADD_BANK_DETAILS = '/add-bank-details';
  static const SEARCH_ADDRESS = '/search-address';
  static const POST_RIDE_STEP_FOUR = '/post-ride-step-four';
  static const MAP_RIDER_CONFIRM_REQUEST = '/map-rider-confirm-request';
  static const MAP_RIDER_SEND_REQUEST = '/map-rider-send-request';
  static const VEHICLE_SETUP = '/vehicle-setup';
  static const WEB_ADD_PAY = '/web-add-pay';
  static const ADD_GIFT = '/add-gift';
  static const CHAT_WITH_EXPERTS = '/chat-with-experts';
  static const WEB_ADD_TO_BANK = '/web-add-to-bank';
  static const MY_RIDES_CONFIRM_DETAILS = '/my-rides-confirm-details';
  static const ARCHIVED = '/archived';
  static const LANGUAGE = '/language';
  static const MY_RIDES_EDIT = '/my-rides-edit';
  static const PREVIOUS_RIDES = '/previous-rides';
  static const PREV_POSTED = '/prev-posted';
}
